services:
  api:
    image: registry.gitlab.com/mrtroll1/cineva/api:latest
    restart: unless-stopped

  nginx:
    image: registry.gitlab.com/mrtroll1/cineva/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    restart: unless-stopped
    depends_on: [api]
