services:
  postgres:
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/src:/app/src:ro
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client/web
      target: dev
    volumes:
      - ./client/web/src:/app/src:ro
      - ./client/web/index.html:/app/index.html:ro
    ports:
      - "5173:5173"
    networks: [cineva_net]

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on: [api, client]
